import "./User.model";
import "./Teacher.model";
import "./Student.model";
import "./Class.model";
import "./Enrollment.model";
import "./Parent.model";
import "./Section.model";
import "./Subject.model";
import "./Attendance.model";
import "./GradeItem.model";
import "./Grade.model";
import "./Outcome.model";
import "./OutcomeProgress.model";
import "./Intervention.model";
import "./QuestionBank.model";
import "./Quiz.model";
import "./QuizQuestion.model";
import "./QuizAttempt.model";
import "./QuizAttemptAnswer.model";
import "./Exam.model";
import "./AdaptiveTrace.model";
import "./ChatLog.model";
import "./Assignment.model";
import "./AssignmentSubmission.model";
import "./PasswordResetOtp.model";
import "./StudentSignupOtp.model";
import "./PlatformSetting.model";
import "./SchoolEvent.model";
import "./EventNotificationRead.model";
import "./AdminAccountActivity.model";

export { User } from "./User.model";
export { Teacher } from "./Teacher.model";
export { Student } from "./Student.model";
export { Parent } from "./Parent.model";
export { Class } from "./Class.model";
export { Enrollment } from "./Enrollment.model";
export { Section } from "./Section.model";
export { Subject } from "./Subject.model";
export { Attendance } from "./Attendance.model";
export { GradeItem } from "./GradeItem.model";
export { Grade } from "./Grade.model";
export { Outcome } from "./Outcome.model";
export { OutcomeProgress } from "./OutcomeProgress.model";
export { Intervention } from "./Intervention.model";
export { QuestionBank } from "./QuestionBank.model";
export { Quiz } from "./Quiz.model";
export { QuizQuestion } from "./QuizQuestion.model";
export { QuizAttempt } from "./QuizAttempt.model";
export { QuizAttemptAnswer } from "./QuizAttemptAnswer.model";
export { Exam } from "./Exam.model";
export { AdaptiveTrace } from "./AdaptiveTrace.model";
export { ChatLog } from "./ChatLog.model";
export { Assignment } from "./Assignment.model";
export { AssignmentSubmission } from "./AssignmentSubmission.model";
export { PasswordResetOtp } from "./PasswordResetOtp.model";
export { StudentSignupOtp } from "./StudentSignupOtp.model";
export { PlatformSetting } from "./PlatformSetting.model";
export { SchoolEvent } from "./SchoolEvent.model";
export { EventNotificationRead } from "./EventNotificationRead.model";
export { AdminAccountActivity } from "./AdminAccountActivity.model";
